spring:
  application:
    name: team-task-manager-backend
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      keepalive-time: 30000
      auto-commit: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 24 hours
frontend:
  url: ${FRONTEND_URL}
logging:
  level:
    org.springframework.security: DEBUG
    com.teammanager: DEBUG
    root: ERROR
    org.springframework.web: DEBUG
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always



